import Head from "next/head";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col h-screen justify-center items-center text-4xl font-semibold">
        <h1>Airbnb Application Clone system</h1>
        <button className=" border px-3 py-1 text-lg mt-3  bg-blue-500 text-white rounded-full">
          Get Started
        </button>
      </main>
    </>
  );
};

export default Home;
